// Generated by CoffeeScript 1.3.3
(function() {
  var test, test_parser, tests, _i, _len;

  test_parser = require('./test_parser');

  tests = test_parser.tests;

  for (_i = 0, _len = tests.length; _i < _len; _i++) {
    test = tests[_i];
    test();
  }

}).call(this);
