// Generated by CoffeeScript 1.3.3
(function() {
  var test, test_formatter, test_parser, tests, _i, _j, _k, _len, _len1, _len2, _ref, _ref1;

  test_parser = require('./test_parser');

  test_formatter = require('./test_formatter');

  tests = [];

  _ref = test_parser.tests;
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    test = _ref[_i];
    tests.push(test);
  }

  _ref1 = test_formatter.tests;
  for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
    test = _ref1[_j];
    tests.push(test);
  }

  for (_k = 0, _len2 = tests.length; _k < _len2; _k++) {
    test = tests[_k];
    test();
  }

}).call(this);
