// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, host, port;

  express = require('express');

  port = 1337;

  host = '0.0.0.0';

  app = express();

  app.get('/tasks', function(req, res) {
    res.set({
      'Content-Type': 'application/json'
    });
    return res.send(['Please fix the site @igor #broken-site status:new', 'This is a done task @igor status:done']);
  });

  app.listen(port);

  console.log("Server running at http://" + host + ":" + port + "/");

}).call(this);
