// Generated by CoffeeScript 1.3.3
(function() {
  var app, express, host, port;

  express = require('express');

  port = 1337;

  host = '0.0.0.0';

  app = express();

  app.get('/', function(req, res) {
    return res.redirect('/');
  });

  app.listen(port);

  console.log("Server running at http://" + host + ":" + port + "/");

}).call(this);
