// Generated by CoffeeScript 1.3.3
(function() {
  var parse;

  parse = function(content, callback) {
    var data, error_message, mentions, mentions_regex, status_regex, statuses, tags, tags_regex;
    if (!content) {
      error_message = 'nothing to parse';
      callback(error_message, null);
      return error_message;
    }
    tags_regex = /(#[a-zA-Z0-9_-]+)/g;
    mentions_regex = /(@[a-zA-Z0-9_-]+)/g;
    status_regex = /(status:[a-zA-Z0-9_-]+)/g;
    tags = content.match(tags_regex || []);
    mentions = content.match(mentions_regex || []);
    statuses = content.match(status_regex || []);
    data = {
      tags: tags,
      mentions: mentions,
      statuses: statuses
    };
    if (callback) {
      callback(null, data);
    }
    return data;
  };

  if (typeof window !== "undefined" && window !== null) {
    if (window.notsoagile == null) {
      window.notsoagile = {};
    }
    window.notsoagile.parse = parse;
  }

  if (typeof module !== "undefined" && module !== null) {
    module.exports = {
      parse: parse
    };
  }

}).call(this);
